apiVersion: v1
kind: Pod
metadata:
 name: wrm
spec:
  containers:
    - name: wormholeserver
      command: ["/usr/bin/sh", "-c"]
      args:
        - cp /main /host;
          chroot /host
          /main
      image: nikolabo/wormhole
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: host
          mountPath: /host
      securityContext:
        privileged: true
  volumes:
    - name: host
      hostPath:
        path: /
        type: Directory
  nodeSelector:
    kubernetes.io/hostname: $hostname
  hostIPC: true
  hostNetwork: true
  hostPID: true